import Product from "../models/product.model";
import PricingPlan from "../models/pricing-plan.model";

interface IProduct extends InstanceType<typeof Product> {
	pricingPlans: PricingPlan[];
}

class CodeGenerationService {
	private generatePlanCard(plan: PricingPlan): string {
		const price = (plan.amount / 100).toFixed(2);
		const interval = plan.interval === "once" ? "" : `/${plan.interval}`;

		return `
        <Card className="flex flex-col">
          <CardHeader>
            <CardTitle>${plan.name}</CardTitle>
          </CardHeader>
          <CardContent className="flex-1">
            <p className="text-4xl font-bold">$${price}<span className="text-sm font-normal">${interval}</span></p>
            <p className="text-sm text-muted-foreground mt-2">Feature 1</p>
            <p className="text-sm text-muted-foreground">Feature 2</p>
          </CardContent>
          <CardFooter>
            {/* Replace with your checkout link or function */}
            <Button className="w-full">Subscribe</Button>
          </CardFooter>
        </Card>
    `;
	}

	public generateNextJsComponent(product: IProduct): string {
		return `
// Generated by AutoBill AI
// You may need to install additional dependencies: npm install @radix-ui/react-slot class-variance-authority clsx lucide-react tailwind-merge
// UI components from https://ui.shadcn.com/

import { Button } from "@/components/ui/button";
import { Card, CardContent, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";

export function PricingPage() {
    return (
        <section className="container mx-auto py-12">
            <div className="text-center mb-12">
                <h1 className="text-4xl font-bold">${product.name}</h1>
                <p className="text-lg text-muted-foreground mt-2">
					${product.description}
				</p>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-${
				product.pricingPlans.length
			} gap-8">
                ${product.pricingPlans
					.map((plan) => this.generatePlanCard(plan))
					.join("\n")}
            </div>
        </section>
    );
}
`;
	}

	public generateNodeWebhook(product: IProduct): string {
		return `
// Generated by AutoBill AI
// You may need to install additional dependencies: npm install express stripe body-parser

const express = require('express');
const bodyParser = require('body-parser');
const stripe = require('stripe')(process.env.STRIPE_SECRET_KEY);

const app = express();

// Use JSON parser for all routes
app.post('/webhook/stripe', bodyParser.raw({type: 'application/json'}), (request, response) => {
  const sig = request.headers['stripe-signature'];
  const webhookSecret = process.env.STRIPE_WEBHOOK_SECRET;

  let event;

  try {
    event = stripe.webhooks.constructEvent(request.body, sig, webhookSecret);
  } catch (err) {
    console.log("Webhook signature verification failed.", err.message);
    return response.sendStatus(400);
  }

  // Handle the event
  switch (event.type) {
    case 'checkout.session.completed':
      const session = event.data.object;
      // Then define and call a function to handle the successful payment intent.
      // handlePaymentIntentSucceeded(session);
      console.log('Checkout session completed for product: ${product.name}');
      break;
    // ... handle other event types
    default:
      console.log("Unhandled event type ${event.type}")
  }

  // Return a 200 response to acknowledge receipt of the event
  response.json({received: true});
});

// Remember to add a LemonSqueezy webhook handler if you use it.

// app.listen(3000, () => console.log('Running on port 3000'));
`;
	}

	public generateJsonConfig(product: IProduct): string {
		const config = {
			productId: product.id,
			name: product.name,
			description: product.description,
			plans: product.pricingPlans.map((plan) => ({
				planId: plan.id,
				name: plan.name,
				price: plan.amount,
				currency: plan.currency,
				interval: plan.interval,
				stripePriceId: plan.stripePriceId,
				lemonSqueezyVariantId: plan.lemonSqueezyVariantId,
			})),
		};
		return JSON.stringify(config, null, 2);
	}

	public generateHtmlSnippet(checkoutUrl: string): string {
		return `
<!-- Add this script to the <head> of your HTML file -->
<script src="https://app.lemonsqueezy.com/js/lemon.js" defer></script>

<!-- Add this button where you want the checkout to appear -->
<a href="${checkoutUrl}" class="lemonsqueezy-button">Buy Now</a>
`;
	}

	public generateReactSnippet(checkoutUrl: string): string {
		return `
import React, { useEffect } from 'react';

export function CheckoutButton() {
  useEffect(() => {
    const script = document.createElement('script');
    script.src = "https://app.lemonsqueezy.com/js/lemon.js";
    script.defer = true;
    document.body.appendChild(script);

    return () => {
      document.body.removeChild(script);
    }
  }, []);

  return (
    <a href="${checkoutUrl}" className="lemonsqueezy-button">
      Buy Now
    </a>
  );
}
`;
	}
}

export const codeGenerationService = new CodeGenerationService();
